name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Build site
      run: mkdocs build
    - name: Clean old files
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name azurestaticsite --auth-mode key -s "\$web"
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name azurestaticsite --auth-mode key -d '$web' -s ./site
    - name: Azure logout
      run: |
            az logout
      if: always()
          
